name: Publish

on:
  workflow_dispatch:
    

jobs:
  test:
    name: Publish
    runs-on: ubuntu-8vcpu-arm 
    environment: production
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: ./.github/actions/setup-node

      - run: pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

        name: Build publishable packages
      - run: pnpm nx run-many -p="tag:npm:public" -t=build

      - name: Print Environment Info
        run: pnpm nx report
        shell: bash

      - name: Publish packages
        run: pnpm nx release publish
        shell: bash
